env:
    credentials: "ENCRYPTED[!f04a7b94c40ef00a0aac378d82a18e74eeb404fd032b51b91ef113b460bd605760875da4f1bc943ea990e3fc85124f73!]"
    rcloneconfig: "ENCRYPTED[!e0000443ab1fd4f71bad01d68454cd8a10ae20846ed24f6c3693ab1a9a1f29895209fa6b42818795ef447beefcccb6e0!]"
    tokentl: "ENCRYPTED[!963ddcbb2853bfcf682883624f0c5d11f748c77aa1bf74c65e48c8a32584637ee5ee93b55a196191c1fbf5e9b63b2ff2!]"
    idtl: "ENCRYPTED[!c453376b5bb33ac159052d8b31ed785e398398e0c92f1bd66dde98959b91aadf17b75c5104bd7485b8da49f1b0fc1e54!]"
    lunch : lunch rr_finix-userdebug
    make: m bacon
 
task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 480m  
  container:
      image: inok2341/anu:latest
      cpu: 8
      memory: 32G
        
  Build-Env-Setup_background_script:
       - export DEBIAN_FRONTEND=noninteractive
       - mkdir -p ~/.config/rclone
       - echo "$rcloneconfig" > ~/.rclone.conf
       - git config --global user.name "darknius09"
       - git config --global user.email "darkniuslightness@gmail.com"
       - echo "$credentials" > ~/.git-credentials
       - git config --global credential.helper store --file=~/.git-credentials
       - rm -rf ~/ccache
       - mkdir -p ~/ccache
       - rclone copy 298:RRQN/ccache.tar.gz ~/ -P
       - cd ~/
       - time tar xf ccache.tar.gz
       - cd ~/
  
  Storage-Checker_background_script:
      - df -h
      - lsblk
      - ls -l -a -h
      - ./s.sh
  
  Sync_script:
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Start sync Source" 
      - mkdir -p ~/rom
      - cd ~/rom
      - rm -rf * .repo
      - repo init -q --no-repo-verify --depth=1 -u https://github.com/Night-Raids-Reborn/manifest-rom -b rr -g default,-mips,-darwin,-notdefault
      - git clone https://github.com/limestonetwo/local_manifest --depth 1 -b lineage .repo/local_manifests
      - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Sync Completed!"

  Build_script:
      - sudo ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build Started"
 #     - ./collect.sh
      - ./final.sh
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build $(cd ~/rom/out/target/product/citrus/ && ls *.zip) Completed!"

  Upload_script:
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Uploading Build..."
      - rclone copy ~/rom/out/target/product/finix/RR-*.zip 298:finix -P
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build $(cd ~/rom/out/target/product/citrus/ && ls *.zip) Uploaded Successfully!"
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Compres ccache"
  #    - ./ziping.sh
      - cd ~/
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Uploading ccache...."
  #    - rclone copy ccache.tar.gz 298:RRQN -P
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Ccache Uploaded Successfully!" 
